### ISSUE TITLE
[Alba] associations with block create anonymous classes and typelizer doesn't handle them well

### ISSUE THREAD

**Issue by okuramasafumi** [skryukov/typelizer#6]
## Problem

```ruby
class FooSerializer
  include Alba::Resource
  many :bars do
    attributes :id, :name
  end
end
```

The code above creates an anonymous class for `bars`, and since it returns `nil` with `name` method, typelizer doesn't work.

I'm implementing a feature that adds a temporary name with `Module#set_temporary_name` method. While it works, there's another problem. As described in [the doc](https://ruby-doc.org/3.3.5/Module.html#method-i-set_temporary_name), a temporary name

> should be nil or non-empty string that is not a valid constant name (to avoid confusing between permanent and temporary names).

so I'm afraid it cannot be used as TypeScript type name.

## Solution

I'd like to propose a `type_name_mapper` config. It's a proc that takes Ruby class name string and returns TS type name. Alba will have its own rule for anonymous class names so it would be possible to convert it with something like below:

```ruby
config.type_name_mapper = ->(name) {
  if name.end_with?('(AlbaAnonymousClass)')
    name.delete_suffix('(AlbaAnonymousClass)')
  else
    name
  end
}
```

**Comment by skryukov** [comment]
Looks like a great addition, thank you @okuramasafumi 🙌

**Comment by davidrunger** [comment]
@okuramasafumi I'm not too sure that I fully understand this issue, so please forgive me if the following comments/questions are misguided.

Could this need be met using the existing `serializer_name_mapper` config option?

```rb
config.serializer_name_mapper = lambda do |serializer|
  name = serializer.name.dup

  name.delete_suffix!('(AlbaAnonymousClass)')

  if name.ends_with?('Serializer')
    name.delete_suffix!('Serializer')
  else
    name.delete_suffix!('Resource')
  end

  name
end
```

Maybe this need could be with the `serializer_name_mapper` config option, but you still think that there would be value in the `type_name_mapper` config option that you are proposing?

Also, to make sure that I understand: in your example, would that generate a `Bar` TypeScript type? And would that type then conflict with / be ambiguous with the `Bar` TypeScript type that would also be generated by a `BarSerializer` or a `BarResource` (if either of those were to exist), and/or the `Bar` TypeScript type that would be generated by a `many :bars` in some other (non-`FooSerializer`) serializer? If so, I somewhat wonder whether using inline definitions in Alba serializers (rather than referencing other serializer class(es) explicitly) simply shouldn't be supported by Typelizer?, since this potential for conflict/ambiguity seems to me to be a significant possible problem.

**Comment by okuramasafumi** [comment]
@skryukov @davidrunger Sorry, I might have not understood the problem correctly. After looking through the source code of typelizer more precisely, now I think we can introduce a different concept for association with block. Since they are not reused and referenced from other serializers, we can make it inline.

I'm writing some code as a PoC, but it takes some time.

**Comment by davidrunger** [comment]
> now I think we can introduce a different concept for association with block. Since they are not reused and referenced from other serializers, we can make it inline

@okuramasafumi Yes, that makes a lot of sense to me! (To be clear / for context, though, I am not a maintainer of this gem, just an interested observer.)
